name: Update Download Stats

on:
  schedule:
    - cron: '0 5 * * *' # Every day at 5am UTC
#  workflow_dispatch:

env:
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:
  update-download-stats:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run update_download_stats.sh
        run: ./update_download_stats.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "download stats auto-update"
          push_options: --force
