name: Update Downloads Count

on:
  schedule:
    - cron: '0 18 * * *' # Every day at 6pm UTC
  workflow_dispatch:

env:
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:
  update-downloads-count:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run generate_downloads_badge.sh
        run: ./generate_downloads_badge.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "downloads count update"
          push_options: --force
